import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const FAQ = () => {
  const faqs = [
    {
      question: "How accurate is the AI detection?",
      answer: "Our AI detection technology achieves 95% accuracy across various content types. We continuously train our models on the latest AI-generated content to maintain this high accuracy rate. The system provides confidence scores so you can assess the reliability of each detection.",
    },
    {
      question: "What types of AI content can you detect?",
      answer: "TrueCheckIA can detect content generated by major AI models including GPT-3, GPT-4, Claude, Bard, and other language models. We support detection across multiple content types including articles, essays, blogs, social media posts, and academic papers.",
    },
    {
      question: "Is there an API available?",
      answer: "Yes! Our REST API is available for Pro and Enterprise plans. It supports real-time detection with response times under 2 seconds. The API includes comprehensive documentation, SDKs for popular programming languages, and webhook support for bulk processing.",
    },
    {
      question: "How does the pricing work?",
      answer: "We offer three plans: Free (10 analyses/month), Pro ($29/month for unlimited analyses), and Enterprise (custom pricing). Annual subscriptions save 20%. All plans include our web interface, and Pro+ plans include API access with different rate limits.",
    },
    {
      question: "Can I cancel anytime?",
      answer: "Absolutely! You can cancel your subscription at any time with no penalties or cancellation fees. Your service will continue until the end of your current billing period, and you can always downgrade to our free plan to continue using basic features.",
    },
    {
      question: "Do you support multiple languages?",
      answer: "Yes, TrueCheckIA supports AI detection in 15+ languages including English, Spanish, French, German, Italian, Portuguese, Dutch, Russian, Chinese, Japanese, and more. Our models are trained on multilingual datasets to ensure accurate detection across different languages.",
    },
  ];

  return (
    <section className="py-24 relative">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16 space-y-4">
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold">
            Frequently Asked{" "}
            <span className="gradient-text">Questions</span>
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Everything you need to know about TrueCheckIA
          </p>
        </div>

        <div className="max-w-3xl mx-auto">
          <Accordion type="single" collapsible className="space-y-4">
            {faqs.map((faq, index) => (
              <AccordionItem
                key={index}
                value={`item-${index}`}
                className="glass rounded-lg px-6 border-border/50"
              >
                <AccordionTrigger className="text-left hover:text-primary transition-colors duration-200 text-lg font-medium">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground leading-relaxed pt-2 pb-4">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>

        <div className="text-center mt-12">
          <p className="text-muted-foreground mb-4">
            Still have questions? We're here to help.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <a
              href="mailto:support@truecheckia.com"
              className="text-primary hover:text-primary/80 transition-colors font-medium"
            >
              Contact Support
            </a>
            <span className="hidden sm:block text-muted-foreground">•</span>
            <a
              href="#"
              className="text-primary hover:text-primary/80 transition-colors font-medium"
            >
              Browse Documentation
            </a>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FAQ;